# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-01-02 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField()),
                ('sepal_width', models.FloatField()),
                ('petal_length', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('species', models.IntegerField(choices=[(0, 'Iris-setosa'), (1, 'Iris-versicolor'), (2, 'Iris-virginica')])),
            ],
        ),
    ]
